# This file was generated by GoReleaser. DO NOT EDIT.
cask "charter" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "e3cd8631e42f2a2b8ec442c65e33c6c9cbbf621cdaf0225b9a76fbf88f9a0946"
      url "https://github.com/use-charter/charter/releases/download/v#{version}/charter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e89886a2d47ccbf197511fc82367406b9b85e43f90710df90e32c33580b63eb3"
      url "https://github.com/use-charter/charter/releases/download/v#{version}/charter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5255c209f34ee8d140126cd48757b537911948dfb97a3be8a56b8d889e73294f"
      url "https://github.com/use-charter/charter/releases/download/v#{version}/charter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a32961f2f60fde508cac1888ab8a0a195bda139d3cfb43847c1460676aa21fb7"
      url "https://github.com/use-charter/charter/releases/download/v#{version}/charter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "charter"
  desc "Offline-first scanner that scores a repo's AI-agent readiness"
  homepage "https://use-charter.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charter"]
    end
  end

  # No zap stanza required

end
